ApplicationHeader As CanvasComponent:
    Fill: =RGBA(0, 0, 0, 0)
    Height: =Max(App.Height, App.MinScreenHeight)/15
    Width: =Max(App.Width, App.MinScreenWidth)
    X: =0
    Y: =0
    ZIndex: =1

    Label2 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        Fill: =RGBA(39, 113, 194, 1)
        Height: =65
        Size: =20
        Text: ="Danphe Hospital Application"
        Width: =1366
        ZIndex: =1

