Applicationfooter As CanvasComponent:
    Fill: =RGBA(0, 0, 0, 0)
    Height: =Max(App.Height, App.MinScreenHeight)/15
    Width: =Max(App.Width, App.MinScreenWidth)
    X: =0
    Y: =0
    ZIndex: =1

    Label2_1 As label:
        Align: =Align.Center
        Color: =RGBA(255, 255, 255, 1)
        Fill: =RGBA(56, 96, 178, 1)
        Height: =65
        Size: =17
        Text: ="Copyright 2023 Quest IT. All rights reserved."
        Width: =1366
        ZIndex: =1

